In [1]:
import pandas as pd

In [2]:
# leyendo el archivo csv
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Agregar una nueva columna

## Agregar una nueva columna con un valor

In [3]:
# agregar una nueva columna al dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## Agregar una nueva columna con un array

El dataframe tiene 1000 filas; por ello, tenemos que crear un array the 1000 elementos

In [4]:
# importar numpy
import numpy as np

In [5]:
# crear un array de 1000 elementos
language_score = np.arange(0, 1000)

In [6]:
# tamaño del array
len(language_score)

1000

In [7]:
# agregar una nueva columna al dataframe con un array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [8]:
# crear numeros enteros aleatorios entre 1 y 100
int_language_score = np.random.randint(1, 100, size=1000)

In [9]:
# el minimo valor es inclusivo y el maximo valor es exclusivo
print(min(int_language_score))
print(max(int_language_score))

1
99

In [10]:
# agregar una nueva columna al dataframe con un array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,64
1,female,group C,some college,standard,completed,69,90,88,98
2,female,group B,master's degree,standard,none,90,95,93,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,13
4,male,group C,some college,standard,none,76,78,75,60
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,71
996,male,group C,high school,free/reduced,none,62,55,55,60
997,female,group C,high school,free/reduced,completed,59,71,65,93
998,female,group D,some college,standard,completed,68,78,77,20
999,female,group D,some college,free/reduced,none,77,86,86,85

In [11]:
# crear numeros decimales aleatorios entre 1 y 100
np.random.uniform(1, 100, size=1000)

array([16.01491398, 92.40050987,  8.33712659, 90.60444632, 33.57080234,
       91.41538889, 69.43638918,  3.511521  , 12.18136476, 84.23214801,
       22.33086103, 71.67842987, 33.19459574, 14.43238655, 99.41471961,
       23.31397105,  8.31980887, 26.24403561, 97.3011412 , 55.59755841,
       66.15479526,  2.76662285, 40.5057043 , 86.07722263, 58.4084458 ,
        8.75346655, 26.9157733 , 14.58028839, 90.79060043, 30.0735013 ,
       87.64260758, 68.52126708, 40.59678451, 85.65454974, 62.95088311,
       55.75766563, 42.65910355, 56.27195481, 90.15245024, 70.94076598,
       39.17370695, 46.19876491, 20.13162999,  9.67580219,  2.34970888,
       49.32224662, 29.68304822, 85.84471565, 96.08476473, 48.60795975,
       29.01239808, 35.10165799, 72.45412095, 78.58917092, 59.17257806,
       67.70041835, 85.56045124, 24.21013881, 77.99357669,  9.82282108,
       76.78059059, 83.6696454 , 12.48625269, 80.431525  , 69.53460238,
       88.12906995, 64.18915913, 11.98177542, 44.08371862,  9.12193731,
        1.87916403, 68.17452382, 59.45531418, 38.07380829, 55.39539757,
        1.08123902, 60.06870438, 65.25225958, 82.37454468, 11.4120477 ,
       25.90511822, 21.60091798, 59.84828762, 11.34814156, 94.33708385,
       69.06291544, 96.77429107, 73.07008387, 32.38790093, 73.36585345,
       17.07281001, 49.67031499, 70.39009145, 73.43523395, 18.60840692,
       25.84003536, 15.46324538, 25.54286247, 64.85179963, 50.30246534,
       12.32099866, 60.2878016 , 96.75909982, 71.67503055, 48.7958883 ,
       37.91608065, 46.44147885,  5.81780717, 23.5944541 , 26.13137715,
       42.39123608, 56.47512891, 31.58313055, 90.99487906, 99.81946799,
       46.85441245, 69.41864375, 31.79743796, 44.29564749, 61.78746126,
       93.50330043, 59.2856747 , 76.41574673, 31.88923097, 84.44147467,
       91.23720202, 11.87899111, 78.75882813,  3.61235235, 20.82783044,
       83.58629246, 78.44068945, 92.20082065, 48.2564432 , 36.103493  ,
       91.57302213, 58.37502866, 38.0793189 , 75.78291088, 70.49916104,
       49.6490049 , 81.47666075,  5.59910191, 93.86308029, 98.94087723,
       35.13241792, 30.13425377, 28.68974309, 81.29696119, 65.97695216,
        2.17519993, 73.03486654, 12.7916167 , 10.92344544, 32.99536351,
       63.48997203, 35.90823532, 68.30356282, 43.63910989, 68.05284417,
       44.55932398, 11.04618553, 15.91833442, 95.4138173 , 46.28988586,
        7.87082427, 83.86347264, 54.9671699 , 57.79511012, 31.32735268,
       88.44893275, 85.17630931, 76.78762164, 97.02062212,  6.09806193,
       63.65527302, 12.85138023, 51.27825219,  8.92323078, 72.77423501,
       67.53985076, 59.26708698, 67.49471073, 78.4416938 , 41.3970902 ,
       16.29119374, 46.95216524, 39.63386055, 89.82733154, 81.25653262,
       72.06236755, 65.54994153, 83.62907313, 73.79330638, 55.20326549,
       49.54793432, 25.11880413, 16.56294241, 72.01840925,  4.57865841,
       46.73921954, 13.05335024, 62.54200469, 21.92852066, 79.48438457,
       35.79937526, 72.9674002 , 38.14482874,  5.05550207, 15.65770359,
        2.89211138, 54.5107801 , 27.49295695, 87.56107837, 62.68598854,
       16.02078306, 36.2415568 , 19.10811474, 24.08111199, 42.60449589,
       42.48971864, 90.74698708, 96.72700544, 11.30680232, 16.98046285,
       56.59511999, 57.40386015, 77.34815644, 20.62666819, 44.71889041,
       88.81209776, 57.04153589, 96.93466302, 98.6114955 ,  2.7751917 ,
       67.96306302, 90.50771703, 32.22367551, 72.07256603, 19.75855401,
       25.6088303 , 76.14184946, 40.95588378, 70.04821783, 90.79591645,
       17.80649104, 45.19948252, 45.43705715, 71.61861335, 16.40651738,
       41.37710821, 37.12925209, 26.42988846, 98.73707236, 34.79108588,
        6.79755684, 62.12043839, 10.6735522 , 24.66328424, 83.93876135,
       77.21221439, 12.79233809, 11.15844108, 57.80401121, 79.36414944,
       64.14994936, 59.84224375, 75.08292237, 81.67428735, 15.18105373,
        1.4284319 , 21.31938778, 87.6810527 , 75.72804372, 57.22503746,
        8.73777716, 78.75393478, 70.88674326, 14.13594537, 38.80780823,
       86.3490299 , 38.05861562, 47.89404659, 95.79443595, 34.38540047,
       97.24983864, 12.16726239, 18.63893141, 22.91637107, 76.89753736,
       37.00699554, 22.6775997 , 62.75173141, 24.71973461, 16.69516039,
       24.0695303 , 11.12509097, 12.94743684, 74.32485717, 79.89660049,
       19.63194755, 85.30657262, 62.58022087, 89.03313444,  3.78062723,
       52.96087328, 81.19100158,  8.43599562, 13.70262677, 60.76824485,
       82.60001383, 60.83003914, 18.79601021, 51.53812134, 91.68484884,
       22.80533114, 42.75580081, 53.8695744 , 59.68426095, 95.50586079,
       61.54850365, 22.78478863, 91.50427353, 48.69626292, 77.64674775,
       16.22597545, 20.65156945,  3.06193538, 15.63260945, 48.28902664,
       41.10856506,  6.24990894, 29.89926434,  2.02155797, 48.9618022 ,
       30.79344928, 85.49547195, 52.28387337, 63.09054343, 89.20751516,
       70.92656429, 80.5074452 , 96.26987458, 51.05081665, 90.64014479,
       13.5475617 , 67.73351165, 55.95250049, 38.9985939 , 50.47812641,
       79.68055506, 82.84799047, 72.10973877, 69.64376275, 62.4284428 ,
       96.29756076,  8.4964356 , 41.31842548, 64.7606395 , 71.78286452,
        3.29167901, 58.80245891, 76.16428398,  6.03847609, 77.77978952,
       36.51269522, 66.01110234, 86.52859433, 36.10655459, 62.83172428,
       78.5129094 , 59.24520345, 76.62634212, 65.91536164, 14.74729854,
       82.69284712, 93.49921054, 52.57624817,  6.42325311, 70.2764801 ,
       31.83148753, 77.49415735, 77.34606098, 62.17066426, 10.35618603,
       16.46953161, 23.26581361, 89.93802364, 70.88553792, 25.82320035,
       72.61436903, 98.45188825, 69.52991566, 84.32217724, 56.29143626,
       16.58519632, 60.7169005 , 11.50497235, 60.37124794, 48.16494398,
       62.88420062, 98.14664797, 49.15786056, 95.71274099, 98.38638755,
       48.49568326, 39.79858371, 65.44488783, 92.41277202, 61.68173526,
       58.36825496, 90.09178524, 71.10065031, 63.03397515, 84.22904365,
       82.11471924, 68.67176279, 46.98005492, 56.60867737, 34.019934  ,
       16.84324484,  4.57662006, 64.69200096, 52.82819722, 46.39036489,
       40.85080486, 69.48525697, 90.23723258, 94.93262079, 71.89502033,
       87.322804  , 50.82433641,  3.79354862, 80.2992358 , 74.49188688,
       37.5447654 , 33.66663457, 76.17613914, 63.80293799, 86.31855856,
       66.85908732, 11.88807915, 66.45131177, 37.73019067, 42.71165683,
       20.5271486 , 22.64800204, 27.96406139, 63.92450649,  6.88011965,
       16.05854231, 76.06789863, 30.32148586, 49.31459884, 38.55052791,
       83.16784667, 32.81850727, 94.92818141, 95.81988688, 85.44050701,
        6.81785081, 52.11344256, 14.42253766, 67.19019475, 74.06589736,
       26.0594396 , 26.10788608, 39.56313428, 82.12917872, 66.49655875,
       28.69680542, 24.25557309, 49.49123413, 93.88432708, 89.99131469,
       84.25613374, 94.33439982, 92.26642651, 78.99638667, 24.97551932,
       19.09309201, 89.87335078, 18.19671424, 57.04505284, 85.16204789,
       57.92902557, 99.9178544 , 80.4181857 , 84.0457752 , 29.03441116,
       77.59231544, 20.03358655, 56.062733  , 80.40117964, 98.34331945,
       93.154321  , 84.78864065, 85.49003209, 79.52773228, 30.29280482,
       33.00583703, 60.9953876 , 52.41780448, 24.2822382 , 54.12647751,
       68.22906334, 20.29390815, 60.10793684, 84.46953634, 43.34736824,
       22.39153713, 12.94181075, 74.01545912, 83.48816011, 81.44180486,
       70.91345084, 85.61002409,  7.37684898, 66.19299469, 32.44289091,
       23.68839049, 15.70334036, 37.85040676, 18.07609622, 32.69771501,
       78.47521178, 18.44445672, 41.55711291,  9.29268674,  2.57084099,
       35.97538632, 34.9426248 , 84.40572673, 83.12552114, 94.84691993,
       84.61229531, 37.74084897, 21.86394428,  9.62650798, 30.12727484,
       98.24299991, 66.14230272, 12.57697446, 46.52347665, 83.32729425,
       72.21186881, 27.84841402, 19.48583444, 75.64609394, 44.31246562,
       51.09329999, 72.57087044, 81.83600889, 64.06260358, 48.71226837,
       25.0307045 , 17.84797443, 22.97442005, 10.87893412, 26.42568487,
       29.43969211, 25.67053598, 75.89272882, 31.11646815, 49.29215263,
       77.4861852 , 53.82379134, 13.88142974, 27.62468557,  1.49753536,
       16.90113792, 50.15520642, 40.33858357, 92.96970854,  1.21274958,
       36.65790943, 98.6669156 , 72.95537408,  7.80447309, 25.79766722,
       49.79870949, 60.25653053,  4.72951356,  1.67816933, 87.86207595,
       34.07960622, 73.54617181, 47.84908385, 89.57893092, 13.86854446,
       13.88151677, 38.25954627, 64.10753545, 34.28251591,  3.91515086,
       26.3411876 , 93.37720516, 70.83048376, 62.49705189, 35.455538  ,
       68.78488797, 35.69902865, 93.15649911, 45.52362593, 87.9511166 ,
       56.80496869, 65.28420248, 25.33723153, 10.23582287, 18.52261103,
       64.66319095, 93.58305865, 23.4319159 , 96.261145  , 67.81563667,
       96.12791936, 72.00669005, 24.12043105, 92.92532322, 93.81202873,
       74.32355524, 27.7930194 , 97.00344126, 88.45177536, 41.45115154,
       47.00957782, 64.54577784, 70.77302583, 70.46302047, 26.86995499,
       77.91134034, 51.03888942, 96.08825695, 18.83438251, 33.95413657,
       84.69993559, 37.28895364, 80.3045513 , 88.52144509, 84.8164936 ,
       17.66147317, 38.66667438, 59.20727195, 47.74717658, 65.99961698,
       73.29525402, 27.59799238, 72.44442663, 65.54871094, 79.7663067 ,
       79.1385104 , 25.49867551, 39.15129798, 13.81120037, 64.70189711,
       66.76015953, 11.07284587, 20.56873365, 90.02905539, 24.66277579,
        4.72359072, 47.96674706, 62.29609877, 41.04574586, 42.77963186,
       40.75956907, 98.00179913,  3.00660455, 33.68972877, 55.84205119,
       25.59210169,  6.94976068, 83.66341299, 51.99418489, 23.72137443,
       15.55328417, 63.16992948,  7.99705301, 67.89251048, 69.05726648,
       75.65499401, 89.83937068, 77.03105947, 69.1721027 , 91.09320746,
       78.39721541, 24.91199058, 16.89619981, 93.047194  , 88.01381261,
       45.84860752, 55.15084523, 55.27977146, 24.14425097, 87.27855844,
       50.57091994,  5.63913753, 52.21819546, 36.05026523, 54.72335708,
       16.16102138, 67.3864486 , 12.54254311, 18.41139405, 47.83862276,
       97.09396156, 76.28436787, 73.50593462, 47.37858245, 28.35480253,
       52.81993813, 91.45716286, 98.69351331, 91.72061417, 18.81171186,
       10.64904139, 61.86050363, 63.502007  , 57.93344543,  2.90846098,
       55.00976556, 94.99861493, 49.43489949, 25.61939229, 53.78328669,
       87.32384887, 78.84833576, 64.88507929, 64.65270834,  6.17106636,
       40.03116893, 74.45295942, 31.49556424, 10.12325575,  8.60898483,
       89.29482137, 40.75071408, 47.97313365, 13.44262111, 32.05006454,
       69.25697332, 48.09737682, 75.51185958,  8.1698489 , 29.72817409,
       21.13197509, 40.98969287, 63.38636324, 68.25718774, 28.79353405,
        4.97429896, 72.949874  ,  6.12978748, 55.75243932, 71.72244553,
       25.72710799, 76.74527354, 93.36866358, 26.30880646, 94.69760699,
       85.36224732, 45.49534383, 44.1287343 , 34.17000471, 34.44469504,
       11.17650943, 79.55679539, 42.28332232, 83.47877376, 55.0599905 ,
       73.76505152, 93.97748131, 29.93500925, 84.06454936, 81.19529076,
       74.03357589, 69.79408579, 35.6376526 , 59.76689084, 71.1120147 ,
        5.57775898, 86.58859767, 32.62024514, 23.09368551, 95.5261267 ,
       28.61730412, 16.79333081, 40.88363435, 83.6094258 , 16.50228142,
       49.16106337, 24.06246099, 10.45184836, 16.47208431, 49.37260988,
       32.41623658, 39.22055092, 68.37657453, 95.54786623, 47.16389957,
        3.7721889 , 67.80444289, 53.44381519,  6.83726781, 65.79237608,
       44.37243227, 19.53562803, 84.70758191, 14.24287628, 68.62472268,
       38.69618878, 58.91920367, 81.23844804, 73.91372123, 40.50548327,
       34.80452517, 15.68443121, 86.39636529, 95.80477054, 67.34148782,
       15.02010468, 63.29760655, 51.38380607,  3.79988017, 73.67192895,
       30.17021647, 92.22353969, 90.97285359, 55.51546115, 95.95872894,
       83.41196509, 27.6246497 , 60.21709763, 26.16391855, 85.75849167,
       23.31870073, 11.93116621, 78.34603736, 11.27247187, 94.6135901 ,
       68.03245548, 59.07088378, 46.68794036, 40.49793093, 53.06889026,
       24.10959211, 17.99662831, 22.11384272, 88.02182419, 22.06252952,
       85.28487701, 85.69478589, 96.28207137, 36.12117269, 98.68048387,
       83.43556288, 16.40920099, 14.01310542, 28.34041666, 18.27568173,
       60.35787439, 34.61771934, 14.88893754, 58.27711625, 67.40007611,
       79.49079115, 51.79116318, 65.23292263, 44.54808898, 68.28917829,
       89.76148185, 31.61726466, 41.06077369, 35.23701097,  1.25008192,
       51.80575627, 63.46425455, 83.17745685, 22.41577542, 92.1935047 ,
       70.17971132, 70.63149148, 30.36597728, 91.37100775,  3.3932432 ,
       26.84539439, 58.25571846, 49.96923229, 59.92744741, 99.04309379,
       36.5047137 , 15.91919694, 63.57566033, 52.1118473 ,  4.56099688,
       28.26018051,  4.6201128 ,  7.1999667 , 66.51620998, 40.15610237,
       19.85598237, 57.2279942 , 93.63653476, 38.38151933, 39.62345403,
       73.08507495, 78.08146488, 15.13626527, 17.41627215, 17.01569201,
       79.41135565, 34.11249318, 61.5401214 , 97.58195829, 51.89820914,
       25.14202725, 86.86103769, 29.88371893, 79.40144517, 76.02636793,
       22.4737422 , 18.80588772, 11.29033938, 52.02627328, 93.85703297,
       26.1207137 , 45.85961747, 92.7495296 , 61.73354806, 75.19061587,
       32.26404881, 40.87284803, 83.04934673, 18.54605069, 33.82366652,
       37.50577495,  7.14916092, 68.71040326, 74.65921223, 63.34280716,
       39.86625066, 82.33696637, 30.98522134, 23.73465275, 21.508855  ,
       48.79783455, 34.77314892, 62.16937891,  7.16761639, 23.11259776,
       59.05587826, 78.60921607, 43.58793239, 93.75439211, 43.80467143,
       93.67711755, 80.90318524, 48.18750822, 36.12181535, 16.08758072,
       19.05004404, 19.51878839, 72.58424023, 86.03127564, 12.93398654,
       81.66759523, 88.8017777 ,  4.63413233,  6.64222478, 23.72791863,
        4.17315182, 61.84866718,  8.67856982, 28.45777507,  9.92173887,
       40.69045665, 39.38397722,  3.11657023, 76.70146984, 60.31814914,
        8.18658358, 84.77839325, 51.79773932, 66.27670023, 27.88195839,
       97.78319996, 84.07035313, 27.18699739, 73.16814644, 71.44647328,
       67.26846618, 87.11280957, 10.51370193, 95.2395779 , 88.81206155,
       76.08806535,  7.25661341, 96.94882163, 82.40756829, 49.59030868])